### ISSUE TITLE
Problem with CDATA when value has newline char

### ISSUE THREAD

**Issue by Aradesh** [doedje/jquery.soap#87] opened 2015-10-05 17:00 UTC
Hi.
I had a problem with sending values with newlines.
Method toString converts <![CDATA[value\nvalue]]> value to &lt;![CDATA[value\nvalue]]&gt; before it will be send to server.
Need to change regexp that detect CDATA to /<!\[CDATA\[[\s\S]*\]\]>/

**Comment by doedje** [comment] 2015-10-06 11:15
I am afraid I don't quite understand what the problem is.... Can you give me an example of your $.soap call that shows me what goes in, what comes out and what you think should come out....
You could use the demo testbed to play around and copy-paste the call and soap.envelope here...

I tried your suggested change but I don't see a difference.

**Comment by avdesign** [comment] 2015-10-23 14:30
Hi, congratulations on the project, am new to jquery and am trying to create this type of call xml.
could help me create this structure. I thank you for your time.

soap12:Envelope >
   soap12:Body>
    SubmitInfo xmlns="http://www.dominio.com/integration">
       entityCode>string</entityCode> 
       xmlDados>string</xmlDados>
     /SubmitInfo>
 /soap12:Body>
/soap12:Envelope>

**Comment by doedje** [comment] 2015-10-23 16:40
I am currently a bit in doubt with this issue... If there is a problem, please give me an example... Else I am afraid I am gonna close the issue.... Sending a pull request which fixes your example would be sweet! ;)

**Comment by Aradesh** [comment] 2015-10-23 16:43
Hi, sorry.
Here you can see that this regexp don't math the string:
https://regex101.com/r/tZ2bC5/1

**Comment by doedje** [comment] 2015-10-23 16:49
Now I understand... but the regexp you supplied one matches newlines.... it should be anything within CDATA

**Comment by Aradesh** [comment] 2015-10-23 16:57
What do you mean? :)

**Comment by avdesign** [comment] 2015-10-23 17:16
Thank you!

 



Anselmo Velame

(11) 96938-4849

 

De: Vladimir Kuleba [mailto:notifications@github.com] 
Enviada em: sexta-feira, 23 de outubro de 2015 14:44
Para: doedje/jquery.soap
Cc: avdesign
Assunto: Re: [jquery.soap] Problem with CDATA when value has newline char (#87)

 

Hi, sorry.
Here you can see that this regexp don't math the string:
https://regex101.com/r/tZ2bC5/1

**Comment by avdesign** [comment] 2015-10-23 17:18
Thank you!

I could understand

 



Anselmo Velame

(11) 96938-4849

 

De: Remy Blom [mailto:notifications@github.com] 
Enviada em: sexta-feira, 23 de outubro de 2015 14:50
Para: doedje/jquery.soap
Cc: avdesign
Assunto: Re: [jquery.soap] Problem with CDATA when value has newline char (#87)

 

Now I understand... but the regexp you supplied one matches newlines.... it should be anything within CDATA

**Comment by Aradesh** [comment] 2015-10-23 17:52
Sorry, my first post has not correct strings :)
This code 
```xml
<![CDATA[value\nvalue]]>
```
converts to this
```xml
&laquo;![CDATA[value\nvalue]]&raquo;
```
and xml fails

**Comment by doedje** [comment] 2015-10-23 19:45
Ah, now I see!!! (I made a typo, in my previous message but also in the code, trying it, but it works now.....)
Care to send me a PR? =]

**Comment by doedje** [comment] 2015-10-24 21:14
I saw your branch, I'll will merge it next week.... no need to send a PR

**Comment by doedje** [comment] 2016-03-07 10:22
fixed

**Closed by doedje** 2016-03-07 10:22 UTC
Labels: awaiting pull request, awaiting response

**Comment by Aradesh** [comment] 2016-03-07 10:58
thanks :+1:
